CRUD Operater
kp26053112/Advance-DataBase pull request #3
Opened 2024-02-08 01:05 UTC by kp26053112

The CRUD operations in MongoDB encompass Create, Read/Retrieve, Update, and Delete, which are fundamental for managing data in MongoDB databases.

Creating new documents in a collection can be achieved through two methods:

1) `insertOne()`: Adds a single document to a collection, returning details about the insertion.
2) `insertMany()`: Inserts multiple documents into a collection at once, providing information about the insertion.

For reading data:

1) `find()`: Retrieves data from a collection, returning a cursor to iterate through matching documents.
2) `findOne()`: Returns a single document object or null if none is found, with optional query criteria.

Updating existing documents involves:

1) `updateOne()`: Modifies a single document matching a specified filter. We can use operations like `$set`, `$unset`, `$inc`, `$push`, and `$pull`.
2) `updateMany()`: Updates multiple documents matching a filter.

Deleting documents is done using:

1) `deleteOne()`: Removes a single document matching a specified filter.
2) `deleteMany()`: Removes multiple documents matching a filter.
3) `drop()`: Removes an entire collection.

These are all codes performed using JavaScript to perform CRUD Operations:

1) insertOne: Inserts a document into the "books" collection with the title "Deep Dive into React Hooks", ISBN "000000000", publication date January 1, 2019, and authored by Ada Lovelace.
2) replaceOne: Updates the document in the "books" collection with the provided ObjectId, replacing its content with updated book details, including a new ISBN, thumbnail URL, and publication date. Verifies the update with a findOne query.
3) updateOne: Updates the document in the "podcasts" collection where the title is "The Developer Hub", adding "databases" and "MongoDB" to its topics array using the `$set` operator. Confirm the update by retrieving the updated document with a findOne query.
4) set: Updates the document with ObjectId "6261a92dfee1ff300dc80bf1" in the "podcasts" collection, setting the "subscribers" field to 98562.
5) push: Adds "Nic Raboy" to the "hosts" array in the document with ObjectId "6261a92dfee1ff300dc80bf1" in the "podcasts" collection using the `$push` operator. Confirm the update by retrieving the document titled "The Developer Hub".
6) upsert: Updates the document in the "podcasts" collection where the title is "The Developer Hub", setting its topics array to ["databases", "MongoDB"]. If the document doesn't exist, it will be created (upserted) with the specified fields and values.
7) updateMany: Updates multiple documents in the "books" collection where the "published date" is before April 27, 2017, setting their "status" field to "NEW".
8) forFindAndModify: Insert a document for "The Atlas Podcast" into the "podcasts" collection, including platforms and download count. This data is inserted to facilitate potential find-and-modify operations.
9) findAndModify: Performs a find-and-modify operation on the document with ObjectId "65c2a217dd77e720d30e243f" in the "podcasts" collection. It increments the "downloads" field by 1 and returns the modified document.
10) insertBird: Inserts data for bird species into the "birds" collection. This data is inserted to facilitate potential delete queries.
11) deleteOne: Deletes a single document from the "birds" collection with the specified ObjectId ("65c2ae34dd77e720d30e2440").
12) deleteMany: Deletes multiple documents from the "birds" collection where the conservation status is "Least Concern".
13) cursorCount: Counts the total number of documents in the "trips" collection. Counts the number of documents in the "trips" collection where the trip duration is greater than 120 minutes and the user type is "Subscriber".
14) cursorSort: Sort documents from the "listingsAndReviews" collection where the bed type is "Real Bed" in ascending order based on the "name" field. Sorts documents from the "listingsAndReviews" collection where the bed type is "Real Bed" in descending order based on the "name" field. Uses projections to simplify the query, returning only the "name" field of the documents. Sorts in ascending and descending order accordingly. Limits the results to 3 documents, filtering by bed type "Real Bed" and property type "Apartment", sorting in descending order based on the "name" field.
15) projection: Find a restaurant in the "restaurants" collection located in Brooklyn and project the "cuisine" and "zipcode" fields. Excludes the "cuisine", "zipcode", and "_id" fields from the result when finding a restaurant in Brooklyn. Excludes the "_id" field and includes the "cuisine" and "zipcode" fields for a restaurant in Brooklyn.

These are all codes performed using Python to perform CRUD Operations:

1) CRUDInsertOne: This Python code connects to a MongoDB Atlas cluster, inserts a new bank account document into the "accounts" collection, and prints the `_id` of the inserted document.
2) CRUDInsertMany: This Python script connects to a MongoDB Atlas cluster and inserts multiple documents representing bank accounts into the "accounts" collection within the "bank" database. It prints the number of documents inserted and their corresponding `_id`s.
3) CRUDUpdateOne: This Python script connects to a MongoDB Atlas cluster and updates a single document in the "accounts" collection within the "bank" database. It increases the "balance" field by 100 for the document with the specified ObjectId. It then prints the original document, the number of modified documents, and the updated document.
4) CRUDUpdateMany: This Python script connects to a MongoDB Atlas cluster and updates multiple documents in the "accounts" collection within the "bank" database. It sets the "minimum_balance" field to 100 for documents where the "account_type" is "savings". It then prints the number of matched documents, the number of modified documents, and the details of one of the updated documents.
5) CRUDFindOne: This Python script connects to a MongoDB Atlas cluster and retrieves a single document from the "accounts" collection within the "bank" database. It searches for a document with the specified ObjectId and prints the result. If found, it prints the document; otherwise, it prints None.
6) CRUDFindMany: This Python script connects to a MongoDB Atlas cluster and retrieves documents from the "accounts" collection within the "bank" database. It searches for documents where the "balance" field is greater than 4700 and prints the results. Finally, it prints the number of documents found.
7) CRUDDeleteOne: This Python script connects to a MongoDB Atlas cluster and deletes a single document from the "accounts" collection within the "bank" database. It searches for a document with the specified ObjectId, prints the document before deletion, performs the deletion, and prints the document after deletion (which should return None). Finally, it prints the number of documents deleted.
8) CRUDDeleteMany: This Python script connects to a MongoDB Atlas cluster and deletes multiple documents from the "accounts" collection within the "bank" database. It searches for documents where the "balance" field is greater than 2000, prints a sample document before deletion, performs the deletion, prints a sample document after deletion (which should return None), and finally prints the number of documents deleted.

2024-02-09 01:30 UTC, chandrikaguntupalli approved these changes
Great job!

2024-02-09 01:54 UTC, chowdeswari10 approved these changes

2024-02-09 23:20 UTC, Tejagni approved these changes

2024-02-20 17:04 UTC, nikshepkulli requested changes
missing files

2024-03-14 16:15 UTC, closed without merging